### ISSUE TITLE
Export Images

### ISSUE THREAD

**Issue by trevore** [oculusinfo/TellFinder#15]
CEOS Users would like the ability to export images from an ad and/or ad group. To view an image one must hover over the icon, however, there is no way to retain that image or have multiple images up to compare them. Additionally, they would like to export images as they have a robust image comparison capability (NetClean) within which they would like to conduct image comparison with ad group images.

**Comment by eric-oculus** [comment]
I will add a right click option to open a new browser tab with the image. The user will then be able to manipulate the image as they choose.

**Comment by eric-oculus** [comment]
Right click on images is implemented and will be available in the next release.
