### ISSUE TITLE
Email occurrence mis-match

### ISSUE THREAD

**Issue by trevore** [oculusinfo/TellFinder#20]
https://tellfinder.istresearch.com:8443/tellfinder/graph.html?clusterid=29581&explorer=false

magictouch182@yahoo.com

When you mouse over the email the summary says that email address appears 41 times, but only appears in the email column of the ad summary 5 times. This is confusing, what's going on here?

For my reference this is issue PILOT-40

**Comment by eric-oculus** [comment]
There is one ad with 35 revisions with the email address magictouch182@yahoo.com. The count is of all revisions of the ad with a given email address. Admittedly, revision management could be improved.
