### ISSUE TITLE
Search phone numbers with special characters

### ISSUE THREAD

**Issue by trevore** [oculusinfo/TellFinder#25]
Analysts would like to be able to search phone numbers without removing dashes and parenthesis. Can tools ignore these, or at least make clear how a phone number should be searched?

PILOT-54

**Comment by eric-oculus** [comment]
In the latest TellFinder, if the search query contains only numbers, parenthesis, dashes and spaces then the query is made against the TellFinder ads_phones database which is normalized. So, users should be able to search for phone numbers as long as they only contain [0-9],(,),-,<space>
