### ISSUE TITLE
Entity Explorer *Alpha* doesn't work from 'Search Attributes' results

### ISSUE THREAD

**Issue by trevore** [oculusinfo/TellFinder#28]
After having done a search using "Search Attributes" (screenshot 1), and one tries to open the Entity Explorer *Alpha* (screenshot 2), the Entity Graph displays instead (screenshot 3).

![image](https://cloud.githubusercontent.com/assets/1606609/6310831/e3115ea8-b90f-11e4-9b84-14606668a7f4.png)

![image](https://cloud.githubusercontent.com/assets/1606609/6310837/eb273130-b90f-11e4-8183-6917647f8fc0.png)

![image](https://cloud.githubusercontent.com/assets/1606609/6310839/f15c5ac6-b90f-11e4-9fe0-314351117eab.png)

**Comment by trevore** [comment]
PILOT-59

**Comment by eric-oculus** [comment]
Yes. The alpha version only works on 'Entity Clusters'. A new version is under development that will work on search results and attributes.
