### ISSUE TITLE
Image search doesn't appear to retrieve the correct results?

### ISSUE THREAD

**Issue by sblzk** [oculusinfo/TellFinder#3]
Searched: https://openads.istresearch.com:8443/openads/graph.html?attributeid=780988, 
Clicked on: cluster "4885510256", 
Double clicked on third picture on second row to search image, got irrelevant results:
(this cluster: https://openads.istresearch.com:8443/openads/graph.html?attributeid=780988)

Also, in that cluster from the search results, similar images were not identified & highlighted even though all the ads pretty much contain the same images.  Unsure if there were subtle differences, or some other anomaly in this case, just wanted to raise it to your attention.

**Comment by eric-oculus** [comment]
There have been lots of changes to image similarity since this bug... It seems to work well now.
