### ISSUE TITLE
Entity Graph cluster linkage clarity

### ISSUE THREAD

**Issue by trevore** [oculusinfo/TellFinder#34]
As it stands right now when a cluster has linkages between itself and multiple other clusters it is visually unclear what attribute links the initial cluster to any specific second cluster. This makes it impossible for analysts to visually follow linkages caused by any specific attribute in this view.

Analysts would like to be able to see the link reasons between specific clusters in the entity graph view as its static nature is less visually overwhelming than the Entity Explorer, but because they cannot currently easily see this information this view is mostly being ignored by SFDA.

PILOT-67

**Comment by eric-oculus** [comment]
In the current graph view, the tooltip for a node indicates "link reasons". This capability is admittedly inadequate.

The new Entity Explorer Alpha is designed to address this problem. Making aggregations and link reasons clear is the primary focus for TellFinder development going forward.
