### ISSUE TITLE
"View Group Details" vs. "Attribute Graph for Ads"

### ISSUE THREAD

**Issue by sblzk** [oculusinfo/TellFinder#4]
What's the difference between the two?  They appear to point to the same place.  Thanks!

**Comment by eric-oculus** [comment]
We still have two kinds of groupings.
  1) "Entities" or "Clusters" are a discrete partitioning of the ads into highly connected sets.
  2) "Attribute" groups represent all the ads with a given attribute. Ads can belong to multiple attribute groups.
