### ISSUE TITLE
Link to GQT broken in "Attribute Graph for Main Phone"

### ISSUE THREAD

**Issue by sblzk** [oculusinfo/TellFinder#6]
The URL for an "Attribute Graph for Main Phone" link I just tried from the new OpenAds, for cluster "easytoremember@mail.ua", is:
http://memexdemo.istresearch.com:7080/gqt_alpha/?query=phone:601121060916

The correct URL is:
http://memexdemo.istresearch.com:7080/gqt-alpha/?query=phone:601121060916

It just needs a hyphen instead of an underscore.

**Comment by eric-oculus** [comment]
GQT links have been updated a few times... Should be fixed now.
